
set_property PACKAGE_PIN P15 [get_ports reset]                    
                set_property IOSTANDARD LVCMOS33 [get_ports reset]
        set_property -dict {PACKAGE_PIN R11 IOSTANDARD LVCMOS33} [get_ports S0]
        set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports S1]
        set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports S2]
        set_property -dict {PACKAGE_PIN V1 IOSTANDARD LVCMOS33} [get_ports S3]
        set_property -dict {PACKAGE_PIN U4 IOSTANDARD LVCMOS33} [get_ports S4]
        set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports {an_out[7]}]
        set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports {an_out[6]}]
        set_property -dict {PACKAGE_PIN C1 IOSTANDARD LVCMOS33} [get_ports {an_out[5]}]
        set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports {an_out[4]}]
        set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {an_out[3]}]
        set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33} [get_ports {an_out[2]}]
        set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {an_out[1]}]
        set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [get_ports {an_out[0]}]
        set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports {enlight_out[2]}]
        set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports {enlight_out[1]}]
        set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {enlight_out[0]}]
        set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {num_out0[7]}]
        set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {num_out0[6]}]
        set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {num_out0[5]}]
        set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports {num_out0[4]}]
        set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS33} [get_ports {num_out0[3]}]
        set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports {num_out0[2]}]
        set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports {num_out0[1]}]
        set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports {num_out0[0]}]
        set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports {num_out1[7]}]
        set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports {num_out1[6]}]
        set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports {num_out1[5]}]
        set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports {num_out1[4]}]
        set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {num_out1[3]}]
        set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [get_ports {num_out1[2]}]
        set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS33} [get_ports {num_out1[1]}]
        set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports {num_out1[0]}]
        set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports {state_out[3]}]
        set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports {state_out[2]}]
        set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports {state_out[1]}]
        set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {state_out[0]}]
       set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVCMOS33} [get_ports beep_r_out]
       set_property -dict {PACKAGE_PIN T1 IOSTANDARD LVCMOS33} [get_ports beep_out]
        set_property -dict {PACKAGE_PIN M6 IOSTANDARD LVCMOS33} [get_ports sd]
        set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports clk]
        set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports {bottle_full}]
        set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS33} [get_ports am_pm]
        
        set_property -dict {PACKAGE_PIN P5 IOSTANDARD LVCMOS33} [get_ports stop]
         set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33} [get_ports toxic]